### ISSUE TITLE
Dropdown Component Children

### ISSUE THREAD

**Issue by kyleharper** [gathercontent/gather-ui#39]
Whilst doing some work moving the components to Style as Config I noticed that `DropdownMenu` has styles for `.dropdown-menu__button-text` and after further investigation I wasn't sure if this is ever used;

```
// Story
<DropdownMenu value="Actions" type="link" caret shouldDisplay items={assets.getDropdownItems()} />

// Component
<Button types={[type]} className="btn--dropdown" clickHandler={this.toggleItems}>
  { value } <span className="dropdown-menu__button-text">{ this.props.children }</span>
  { caret && <FontAwesomeIcon name="fa-caret-down" /> }
</Button>
```

Does the `value` prop and `children` do the same thing? It'd be worth adding a story to show how we could use both props OR replace `value` with `children` in the story as it looks like `Button` will handle the rendering of children anyway.

**Comment by magalhini** [comment]
@kyleharper so I noticed why this is the case, I had forgotten before why this component was accepting both value and children.

There is one exception scenario where we don't want the `value` but we want a `children` to render, and that is the settings dropdown in each Project Unit. That little cog icon is using the Dropdown menu, and it's also the only place not using the `caret` as an option.

I've refactored the component a little bit, however:

- That component shouldn't be a dropdown, IMO. Maybe a Dropdown Switcher? I believe it's the only thing making this component trying to do and be too much!
- Should we make a note to clean it up in the future? I don't think doing it now is a good idea (time scope) but it's worth discussing if it should become a separate pattern.

**Comment by kyleharper** [comment]
👍  to all your points. Leave this issue open so we can come back to it when one of us have some free time to fix this.

**Comment by kyleharper** [comment]
Something to note;

We could replace `DropdownSwitcher` with the `DropdownMenu` component and remove the switcher from the library with your latest edits to DropdownMenu 👍

**Comment by kyleharper** [comment]
Closed due to new Dropdown components 👍
